monolog:
    channels:
        - deprecation
        - mailer

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

            mailer:
                type: stream
                path: "%kernel.logs_dir%/mailer.log"
                level: debug
                channels: ["mailer"]